spring:
  datasource:
    url: jdbc:mysql://localhost/framework
    username: root
    password: root
spring:
  datasource:
    url: jdbc:mysql://localhost/framework
    username: root
    password: root